### ISSUE TITLE
آمار در ایندکس

### ISSUE THREAD

**Issue by Masoud-MI** [MyBBIr/MyBBPersian#10]
سلام
در صفحه ایندکس قسمت چندین متن اشتباه ترجمه شده موجود هست:
1- نوشته ما (مثلا 2) کاربر کاربر شده داریم
2- می نویسه متولید امروز
3- نوشته بیشتر تعداد بازدید

صحیحش این هست:
1- ما در اینجا 2 کاربر عضو شده داریم
2- متولد امروز
3- بیشترین تعداد بازدید از این انجمن

**Comment by ATofighi** [comment]
این مشکل قبلن گزارش شده است:
#9
