### ISSUE TITLE
غلط املایی در بخش عضویت 

### ISSUE THREAD

**Issue by Amirreza78** [MyBBIr/MyBBPersian#26]
سلام .
اینو یکی از کاربران گزارش داده بود :
سلام توی بخش عضویت در مای بی بی ۱.۸ شما مشاهده می کنید که عبارت : تکرار کلمه عبور ؛ به شکل عبوره  نوشته شده است.

**Comment by ATofighi** [comment]
مورد دوم به #29 منتقل شد.
