### ISSUE TITLE
غلط املایی در بخش پروفایل

### ISSUE THREAD

**Issue by mersadnouri** [MyBBIr/MyBBPersian#27]
سلام
توی پروفایل های مای بی بی 1.8 تو قسمت برای نمایش تعداد پست ها هستش
1.تعداد ارسال ها
2.تعداد موضوع ها

خب اگه دقت کنید میبینید برای هر دو نوشته تعداد ارسال ها در صورتی که باید به جای تعداد ارسال دومی تعداد موضوع ها نوشته شده باشه!

با تشکر

**Comment by ATofighi** [comment]
تکراری #20
