### ISSUE TITLE
لیست دشمنان

### ISSUE THREAD

**Issue by ATofighi** [MyBBIr/MyBBPersian#29]
اوکی ولی یع غلط املایی دیگه هم هست وقتی یکی برات درخواست دوستی میده بعد یه پیام برات میاد که نوشته لیست دوستان /دشمنان به جای لیست دوستان/سیاه 
@Amirreza78

**Comment by ATofighi** [comment]
لیست دشمنان با لیست سیاه معنی یکسانی دارند.

**Comment by Big-Goal** [comment]
سلام،البته لیست سیاه بهتره،چون لیست دشمنان بار منفی خیلی قویتری داره که در یک انجمن چنین معنایی قطعا مدنظر نخواهد بود.

**Comment by Amirreza78** [comment]
از نظر من هم لیست سیاه بهتره .
