### ISSUE TITLE
مجموع موضوع‌ها

### ISSUE THREAD

**Issue by Masoud-MI** [MyBBIr/MyBBPersian#31]
سلام به همگی
وقتی یه پروفایل رو باز می کنی، تو تب اطلاعات انجمن دوبار نوشته شده "مجموع ارسال ها" که اولیش درسته اما دومی باید بشه "مجموع موضوع ها" پس لطفا مشکل رو رفع کنید
ممنون

**Comment by ATofighi** [comment]
عزیز دل این تا الآن ۳ بار گزارش شده و رفع شده:|
