### ISSUE TITLE
افراد حاضر در انجمن

### ISSUE THREAD

**Issue by Big-Goal** [MyBBIr/MyBBPersian#37]
تبدیل افراد حاضر  در انجمن به افراد آنلاین

**Comment by ATofighi** [comment]
آنلاین یک کلمه‌ی بیگانه‌تر از حاضر هست.

**Comment by Big-Goal** [comment]
یکم منطقی و عالمانه تر فکر کن؛ مثل بعضی ها فکر نکن که میگن هر کلمه و حرف و حرکه ای که از زبان بیگانه وارد بشه حتما باید ترجمه و بومی سازی بشه!
این تفکر بجز در ایران در هیچ کجای دنیا رواج نداره.

البته ما باید همیشه حافظ و حامی زبان خودمون باشیم و تلاش کنیم تا زبان خودمون رو به بهترین وجه نگهداری کنیم اما این به این معنی نیست که جلو هرگونه تبادل فرهنگی رو بگیریم.

منم میگم همه باید قرص و محکم از فرهنگ و زبان خودشون محافظت کنن اما این به این معنا نیست که زبان رو ایزوله کنی و نذاری تبادل درش ایجاد بشه،چون که تبادل موجب غنی تر شدن هر زبانی میشه

الان خود انگلیسی نیم میلیون کمله داره و غنی ترین زبان جهان هست؛قسمت اعظم این اتفاق بخاطر تبادل فرهنگیش با زبان های دیگس.

حرف آخرم اینکه قدر زبان خودمون رو بدونیم اما نباید محصور زبان باشیم چون هرچی باشه فقط یک وسیله هست.

**Comment by ATofighi** [comment]
> یکم منطقی و عالمانه تر فکر کن؛ مثل بعضی ها فکر نکن که میگن هر کلمه و حرف و حرکه ای که از زبان بیگانه وارد بشه حتما باید ترجمه و بومی سازی بشه!
> این تفکر بجز در ایران در هیچ کجای دنیا رواج نداره.
> البته ما باید همیشه حافظ و حامی زبان خودمون باشیم و تلاش کنیم تا زبان خودمون رو به بهترین وجه نگهداری کنیم اما این به این معنی نیست که جلو هرگونه تبادل فرهنگی رو بگیریم.
> منم میگم همه باید قرص و محکم از فرهنگ و زبان خودشون محافظت کنن اما این به این معنا نیست که زبان رو ایزوله کنی و نذاری تبادل درش ایجاد بشه،چون که تبادل موجب غنی تر شدن هر زبانی میشه
> الان خود انگلیسی نیم میلیون کمله داره و غنی ترین زبان جهان هست؛قسمت اعظم این اتفاق بخاطر تبادل فرهنگیش با زبان های دیگس.
> حرف آخرم اینکه قدر زبان خودمون رو بدونیم اما نباید محصور زبان باشیم چون هرچی باشه فقط یک وسیله هست.

در کل کوتاه سازی شامل موارد زیر می‌شه:
- تغییر فعل‌های بلند و دشوار به فعل‌های ساده
- حذف کلمات مترادف اگه تکرار شده باشه توی جمله
- استفاده از لغات کوتاه‌تر فارسی به جای لغات بلند فارسی

همچنین در این مورد بهتره 
`افراد حاضر در انجمن`
به
`افراد حاضر`
تبدیل بشه.

**Comment by Big-Goal** [comment]
آره افراد حاضر هم خوبه
:+1:
