### ISSUE TITLE
تیم مدیریتی انجمن

### ISSUE THREAD

**Issue by Big-Goal** [MyBBIr/MyBBPersian#38]
تبدیل تیم مدیریتی انجمن به تیم مدیریت

**Comment by ATofighi** [comment]
https://github.com/mybb/mybb/blob/feature/inc/languages/english/index.lang.php#L17

**Comment by Big-Goal** [comment]
عزیز دل برادر منم میدونم که اینا بطور دقیق از متن انگلیسی ترجمه شدن، اما اصلا نیازی نیست که هرچی تو ورژن انگلیسی آورده ما هم دقیقا اونو ترجمه کنیم.
چون متن ها و کلمات،کلمه تخصصی نیستن که کاربرا رو به اشتباه بندازن،
فردی هم که اینا رو در ورژن انگلیسی نوشته،یکی هست مثل من و شما که یک اسم عادی واسه هر بخش گذاشته نه اسم تخصصی

**Comment by ATofighi** [comment]
این حرف شما قبول، ولی در کل کوتاه‌سازی کلمات یکی از اهداف ارائه این فارسی‌ساز نیست و ممکنه باعث ایجاد ابهام در برخی موارد بشه،

البته این مورد جزءش نیست.

**Comment by Big-Goal** [comment]
قطعا وقتی یک کلمه رو کوتاهش میکنم این مورد رو در نظر دارم،اگه دقت کنی واسه یکی از موارد کوتاه سازی لیبل پیشنهاد دادم،چون احساس کردم ممکنه ابهام داشته باشه؛ پس در این مورد نگران نباش

**Comment by ATofighi** [comment]
@MyBBIr/collaborator نظر بقیه چیه؟

**Comment by Amirreza78** [comment]
تیم مدیریت بهتره
