### ISSUE TITLE
پیوند سایتی آراِس‌اِس

### ISSUE THREAD

**Issue by Big-Goal** [MyBBIr/MyBBPersian#40]
تبدیل پیوند سایتی آراِس‌اِس به پیوند RSS

**Comment by ATofighi** [comment]
به دلایلی بهتر هست از لغات انگلیسی استفاده نشود.

**Comment by Big-Goal** [comment]
بابا این 
RSS
جهانیه. اینی هم که تو نوشتی آراس اس فقط با حروف فارسیه وگرنه خود کلمه باز انگلیسی هست

**Comment by ATofighi** [comment]
بله میدونم،
یکسری مشکلات در یکی از سیستم عامل‌ها توی نمایش این قبیل کلمات انگلیسی پیش اومده بود که اینها رو به صورت فارسی نوشتیم، درکل موارد خیلی بهتری  برای کوتاه سازی در جملات بلندی که در فارسی‌ساز استفاده شده به چشم میخورن.

**Comment by Big-Goal** [comment]
آره اما این مورد رو نه بخاطر کوتاه کردن بلکه بخاطر ناخوشایند جلوه دادن بهتره تغییر بدیم،یک مورد دیگه هم اینکه این گزینه رو همه با کلمه 
rss 
یا لوگو
RSS rss
میشناسن

**Comment by ATofighi** [comment]
@MyBBIr/collaborator

**Comment by Amirreza78** [comment]
ببینید ! 
شاید دیده باشید که بعضی وقت ها اگه یه جایی کلمه انگلیسی یا حتی عدد(!)باشه ، کل جمله به مهم ریخته میشه
مثلاً نصف جمله میره اونور عدد یا کلمه اینگلیسی و ...
پس بهتره فارسی باشه !

**Comment by ATofighi** [comment]
@MyBBIr/collaborator نظر بدید.

**Comment by Amirreza78** [comment]
@Atofighi شاید فقط ما به گیت هاب سر میزنیم !

**Comment by ATofighi** [comment]
به بقیه‌ی مدیران ایمیل میشه اینا! :) باید چک کنن! :)
