### ISSUE TITLE
 بارگزاری مجدد این صفحه

### ISSUE THREAD

**Issue by Big-Goal** [MyBBIr/MyBBPersian#41]
تغییر  بارگزاری مجدد این صفحه به بارگذاری مجدد

**Comment by ATofighi** [comment]
https://github.com/mybb/mybb/blob/feature/inc/languages/english/online.lang.php#L89

**Comment by Big-Goal** [comment]
یک موردی که تو بهش توجه نمیکنی این هست که به این عبارات بصورت مطلق نگاه میکنی یعنی مثلا میگی عبارت بارگذاری مجدد گنگه یا مبهمه یا...
در حالی که باید به موقعیتی که این عبارات در اون قرار گرفتن هم توجه کنی.

عبارت بارگذاری مجدد در صفحه افراد آنلاین زیر افراد باکس افراد آنلاین قرار گرفته.
حالا بنظرت گزینه بارگذاری مجدد در چنین موقعیتی چه مفهومی میتونه داشته باشه؟

الان یک پیشنهاد جدید بنظرم رسید: چطوره بارگزاری مجدد این صفحه رو به تازه سازی صفحه تغییر بدیم؟

**Comment by ATofighi** [comment]
خوبه! :)

2015-02-03 19:10 GMT+03:30 Big-Goal notifications@github.com:

> یک موردی که تو بهش توجه نمیکنی این هست که به این عبارات بصورت مطلق نگاه
> میکنی یعنی مثلا میگی عبارت بارگذاری مجدد گنگه یا مبهمه یا...
> در حالی که باید به موقعیتی که این عبارات در اون قرار گرفتن هم توجه کنی.
> 
> عبارت بارگذاری مجدد در صفحه افراد آنلاین زیر افراد باکس افراد آنلاین قرار
> گرفته.
> حالا بنظرت گزینه بارگذاری مجدد در چنین موقعیتی چه مفهومی میتونه داشته باشه؟
> 
> الان یک پیشنهاد جدید بنظرم رسید: چطوره بارگزاری مجدد این صفحه رو به تازه
> سازی صفحه تغییر بدیم؟
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MyBBIr/MyBBPersian/issues/41#issuecomment-72672185.

## 

گروه پشتیبانی مای‌بی‌بی در ایران http://my-bb.ir
