### ISSUE TITLE
لیست اعضا

### ISSUE THREAD

**Issue by Big-Goal** [MyBBIr/MyBBPersian#42]
تغییر لیست اعضا به اعضا

**Comment by ATofighi** [comment]
https://github.com/mybb/mybb/blob/feature/inc/languages/english/global.lang.php#L13

**Comment by ATofighi** [comment]
این مورد «اعضا» به تنهایی از نظر من ابهام ایجاد میکنه.

**Comment by Big-Goal** [comment]
میدونم چرا اینو میگی،منم وقتی از دید مدیر انجمن به این گزینه با این عبارت یعنی اعضا نگاه میکنم؛ به قول تو یه احساس ابهام و عجیب بودن بهم دست میده،این بخاطر اینه که ما به این کلمه عادت کردیم.
اما خودتو جای یه کاربر عادی بذار که داره تو یه انجمن میگرده؛اونوقت گزینه اعضا براش خیلی عادی هست.

سردر-انجمن-اعضا-تقویم-راهنما

با این همه من رو این گزینه زیاد پافشاری نمیکنم؛ اگه خواستی میبندمش چون زیادم طولانی نیست..
