### ISSUE TITLE
چه کسانی امروز در انجمن حضور داشته اند

### ISSUE THREAD

**Issue by Big-Goal** [MyBBIr/MyBBPersian#43]
تغییر چه کسانی امروز در انجمن حضور داشته اند به کاربران آنلاین امروز

**Comment by ATofighi** [comment]
همان طور که گفته شده آنلاین از حضور بیگانه‌تر هست.

**Comment by Big-Goal** [comment]
همانطور که گفته شد یکی دو مورد اون هم به این شکل مشکلی نداره.
https://github.com/MyBBIr/MyBBPersian/issues/37
(:
