### ISSUE TITLE
مرتب سازی بر اساس

### ISSUE THREAD

**Issue by Big-Goal** [MyBBIr/MyBBPersian#47]
تغییر مرتب سازی بر اساس به چینش بر اساس در جاهای مختلف مخصوصا 
ها select

**Comment by ATofighi** [comment]
طبق http://my-bb.ir/Thread-sort تایید نشد و از مرتب‌سازی استفاده خواهد شد.

**Comment by Big-Goal** [comment]
اخه عزیز من این مورد چیزی نیست که به نظرسنجبی نیاز داشته باشه.
یه بار با موبایل بیا تو انجمن اونوقت میبینی گزینه های سلکتورا کل صفحه رو میگیرن.
دیگه این چیزا رو واسه نظرسنجی نمیذارن که
باید تخصصی و با چنین معیارهایی بررسیشون کرد

**Comment by ATofighi** [comment]
نظرسنجی‌ای که ایجاد شد هرکی شرکت کرد تخصص داشت توی زمینه‌ی وب و این نظرش بود.

در کل این مورد اصلن چیز مهمی نیست! وقتی خود MyBB 1.x ریسپانسیو نیست :)

به راحتی با ریسایز این چیزا به سایز کوچک توی رزولیشن‌های پایین مشکل رفع میشه برای یک طراحی ریسپانسیو و نیاز به تغییر کلمه، به کلمه‌ای که توسط اکثر افراد نسبت به کلمه‌ی قبلی مورد قبول واقع نشده کار جالبی نیست.

**Comment by Big-Goal** [comment]
شما از اون طرف که تخصص داشت تو اون نظرسنجی نظر شخصی و سلیقه ایشو پرسیده بودی یا نظر تخصصی همراه با دلیل؟
من اینجا نظر شخصیمو در این رابطه نمیگم،نظر تخصصیمو همراه با دلیل و مدرک میگم.ولی تو اونجا از اونا بدون هیچ مقدمه و توضیحی فقط نظر شخصی و سلیقه ایشون رو پرسیدی
